### ISSUE TITLE
tsv output 

### ISSUE THREAD

**Issue by Avitzm** [cdanielmachado/carveme_paper#2]
Can you please provide the column titles of the tsv ouput file? 
Thanks!

**Comment by cdanielmachado** [comment]
Hi, the output TSV file comes from DIAMOND, you can find in their documentation more details about the columns:

https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options

In particular:

"By default, there are 12 preconfigured fields: qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore."

**Comment by Avitzm** [comment]
Could you please also explain the xml file or tell me where to find a full description of it?
Thanks

**Comment by cdanielmachado** [comment]
Sure, the models are in SBML format: http://sbml.org/Main_Page
