### ISSUE TITLE
Benchmark to python3

### ISSUE THREAD

**Issue by arianccbasile** [cdanielmachado/carveme_paper#3]
Hi Daniel :) 
I am trying to use your benchmark to analyse some models I just created and I noticed that your script are working with framed and python 2, I was thinking of moving the scripts to python 3 as cplex is dropping python 2. Any chance you have already moved the code to reframed and python 3? If this is the case, may I have the link to that? 

Best,
Arianna

**Comment by cdanielmachado** [comment]
Hi Arianna,

Yes, it is now inside of CarveMe's internal benchmark code:

https://github.com/cdanielmachado/carveme/blob/master/carveme/cli/benchmark.py

☺️

**Comment by arianccbasile** [comment]
Thank you :)
